/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kerlinmichel' at '1/1/17 5:23 PM' with Gradle 2.10
 *
 * @author kerlinmichel, @date 1/1/17 5:23 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
